### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by Isaachhh** [anguyen8/vision-llms-are-blind#1]
Wonderful work!

You mentioned that you fine-tuned a SOTA 7B model Bunny to see the influence of fine-tuning. Is the model you used Bunny-Llama-3-8B-V? Thanks!

BTW, you marked the Bunny paper as two different citing items (14 and 15).

![Screenshot 2024-07-13 at 12 10 43](https://github.com/user-attachments/assets/355a58c0-5e28-4ccf-96f5-d163f82a8b04)
![Screenshot 2024-07-13 at 12 12 43](https://github.com/user-attachments/assets/645124e1-318c-4314-8798-8eb6e9bb76a6)

**Comment by anguyen8** [comment]
@taesiri Could you chime in?

**Comment by taesiri** [comment]
Hello @Isaachhh 

We used `Bunny-v1.1-Llama-3-8B-V` and the original weights can be found [here](https://huggingface.co/BAAI/Bunny-v1_1-Llama-3-8B-V).

**Comment by Isaachhh** [comment]
Got it! Thank you very much!
